package adb

type KeyEvent int

const (
	KEYCODE_UNKNOWN KeyEvent = iota
	KEYCODE_SOFT_LEFT
	KEYCODE_SOFT_RIGHT
	KEYCODE_HOME
	KEYCODE_BACK
	KEYCODE_CALL
	KEYCODE_END
	KEYCODE_0
	KEYCODE_1
	KEYCODE_2
	KEYCODE_3
	KEYCODE_4
	KEYCODE_5
	KEYCODE_6
	KEYCODE_7
	KEYCODE_8
	KEYCODE_9
	KEYCODE_STAR
	KEYCODE_POUND
	KEYCODE_DPAD_UP
	KEYCODE_DPAD_DOWN
	KEYCODE_DPAD_LEFT
	KEYCODE_DPAD_RIGHT
	KEYCODE_DPAD_CENTER
	KEYCODE_VOLUME_UP
	KEYCODE_VOLUME_DOWN
	KEYCODE_POWER
	KEYCODE_CAMERA
	KEYCODE_CLEAR
	KEYCODE_A
	KEYCODE_B
	KEYCODE_C
	KEYCODE_D
	KEYCODE_E
	KEYCODE_F
	KEYCODE_G
	KEYCODE_H
	KEYCODE_I
	KEYCODE_J
	KEYCODE_K
	KEYCODE_L
	KEYCODE_M
	KEYCODE_N
	KEYCODE_O
	KEYCODE_P
	KEYCODE_Q
	KEYCODE_R
	KEYCODE_S
	KEYCODE_T
	KEYCODE_U
	KEYCODE_V
	KEYCODE_W
	KEYCODE_X
	KEYCODE_Y
	KEYCODE_Z
	KEYCODE_COMMA
	KEYCODE_PERIOD
	KEYCODE_ALT_LEFT
	KEYCODE_ALT
	KEYCODE_SHIFT_LEFT
	KEYCODE_SHIFT
	KEYCODE_TAB
	KEYCODE_SPACE
	KEYCODE_SYM
	KEYCODE_EXPLORER
	KEYCODE_ENVELOPE
	KEYCODE_ENTER
	KEYCODE_DEL
	KEYCODE_GRAVE
	KEYCODE_MINUS
	KEYCODE_EQUALS
	KEYCODE_LEFT_BRACKET
	KEYCODE_RIGHT_BRACKET
	KEYCODE_BACKSLASH
	KEYCODE_SEMICOLON
	KEYCODE_APOSTROPHE
	KEYCODE_SLASH
	KEYCODE_AT
	KEYCODE_NUM
	KEYCODE_HEAD
	KEYCODE_FOCUS
	KEYCODE_PLUS
	KEYCODE_MENU
	KEYCODE_NOTIFICATION
	KEYCODE_SEARCH
	KEYCODE_MEDIA_PLAY_PAUSE
	KEYCODE_MEDIA_STOP
	KEYCODE_MEDIA_NEXT
	KEYCODE_MEDIA_PREVIOUS
	KEYCODE_MEDIA_REWIND
	KEYCODE_MEDIA_FAST_FORWARD
	KEYCODE_MUTE
)

// KeyEvents is a map of key events to their corresponding key codes.
var KeyEvents = map[KeyEvent]string{
	KEYCODE_UNKNOWN:            "KEYCODE_UNKNOWN",
	KEYCODE_SOFT_LEFT:          "KEYCODE_SOFT_LEFT",
	KEYCODE_SOFT_RIGHT:         "KEYCODE_SOFT_RIGHT",
	KEYCODE_HOME:               "KEYCODE_HOME",
	KEYCODE_BACK:               "KEYCODE_BACK",
	KEYCODE_CALL:               "KEYCODE_CALL",
	KEYCODE_END:                "KEYCODE_END",
	KEYCODE_0:                  "KEYCODE_0",
	KEYCODE_1:                  "KEYCODE_1",
	KEYCODE_2:                  "KEYCODE_2",
	KEYCODE_3:                  "KEYCODE_3",
	KEYCODE_4:                  "KEYCODE_4",
	KEYCODE_5:                  "KEYCODE_5",
	KEYCODE_6:                  "KEYCODE_6",
	KEYCODE_7:                  "KEYCODE_7",
	KEYCODE_8:                  "KEYCODE_8",
	KEYCODE_9:                  "KEYCODE_9",
	KEYCODE_STAR:               "KEYCODE_STAR",
	KEYCODE_POUND:              "KEYCODE_POUND",
	KEYCODE_DPAD_UP:            "KEYCODE_DPAD_UP",
	KEYCODE_DPAD_DOWN:          "KEYCODE_DPAD_DOWN",
	KEYCODE_DPAD_LEFT:          "KEYCODE_DPAD_LEFT",
	KEYCODE_DPAD_RIGHT:         "KEYCODE_DPAD_RIGHT",
	KEYCODE_DPAD_CENTER:        "KEYCODE_DPAD_CENTER",
	KEYCODE_VOLUME_UP:          "KEYCODE_VOLUME_UP",
	KEYCODE_VOLUME_DOWN:        "KEYCODE_VOLUME_DOWN",
	KEYCODE_POWER:              "KEYCODE_POWER",
	KEYCODE_CAMERA:             "KEYCODE_CAMERA",
	KEYCODE_CLEAR:              "KEYCODE_CLEAR",
	KEYCODE_A:                  "KEYCODE_A",
	KEYCODE_B:                  "KEYCODE_B",
	KEYCODE_C:                  "KEYCODE_C",
	KEYCODE_D:                  "KEYCODE_D",
	KEYCODE_E:                  "KEYCODE_E",
	KEYCODE_F:                  "KEYCODE_F",
	KEYCODE_G:                  "KEYCODE_G",
	KEYCODE_H:                  "KEYCODE_H",
	KEYCODE_I:                  "KEYCODE_I",
	KEYCODE_J:                  "KEYCODE_J",
	KEYCODE_K:                  "KEYCODE_K",
	KEYCODE_L:                  "KEYCODE_L",
	KEYCODE_M:                  "KEYCODE_M",
	KEYCODE_N:                  "KEYCODE_N",
	KEYCODE_O:                  "KEYCODE_O",
	KEYCODE_P:                  "KEYCODE_P",
	KEYCODE_Q:                  "KEYCODE_Q",
	KEYCODE_R:                  "KEYCODE_R",
	KEYCODE_S:                  "KEYCODE_S",
	KEYCODE_T:                  "KEYCODE_T",
	KEYCODE_U:                  "KEYCODE_U",
	KEYCODE_V:                  "KEYCODE_V",
	KEYCODE_W:                  "KEYCODE_W",
	KEYCODE_X:                  "KEYCODE_X",
	KEYCODE_Y:                  "KEYCODE_Y",
	KEYCODE_Z:                  "KEYCODE_Z",
	KEYCODE_COMMA:              "KEYCODE_COMMA",
	KEYCODE_PERIOD:             "KEYCODE_PERIOD",
	KEYCODE_ALT_LEFT:           "KEYCODE_ALT_LEFT",
	KEYCODE_ALT:                "KEYCODE_ALT",
	KEYCODE_SHIFT_LEFT:         "KEYCODE_SHIFT_LEFT",
	KEYCODE_SHIFT:              "KEYCODE_SHIFT",
	KEYCODE_TAB:                "KEYCODE_TAB",
	KEYCODE_SPACE:              "KEYCODE_SPACE",
	KEYCODE_SYM:                "KEYCODE_SYM",
	KEYCODE_EXPLORER:           "KEYCODE_EXPLORER",
	KEYCODE_ENVELOPE:           "KEYCODE_ENVELOPE",
	KEYCODE_ENTER:              "KEYCODE_ENTER",
	KEYCODE_DEL:                "KEYCODE_DEL",
	KEYCODE_GRAVE:              "KEYCODE_GRAVE",
	KEYCODE_MINUS:              "KEYCODE_MINUS",
	KEYCODE_EQUALS:             "KEYCODE_EQUALS",
	KEYCODE_LEFT_BRACKET:       "KEYCODE_LEFT_BRACKET",
	KEYCODE_RIGHT_BRACKET:      "KEYCODE_RIGHT_BRACKET",
	KEYCODE_BACKSLASH:          "KEYCODE_BACKSLASH",
	KEYCODE_SEMICOLON:          "KEYCODE_SEMICOLON",
	KEYCODE_APOSTROPHE:         "KEYCODE_APOSTROPHE",
	KEYCODE_SLASH:              "KEYCODE_SLASH",
	KEYCODE_AT:                 "KEYCODE_AT",
	KEYCODE_NUM:                "KEYCODE_NUM",
	KEYCODE_HEAD:               "KEYCODE_HEAD",
	KEYCODE_FOCUS:              "KEYCODE_FOCUS",
	KEYCODE_PLUS:               "KEYCODE_PLUS",
	KEYCODE_MENU:               "KEYCODE_MENU",
	KEYCODE_NOTIFICATION:       "KEYCODE_NOTIFICATION",
	KEYCODE_SEARCH:             "KEYCODE_SEARCH",
	KEYCODE_MEDIA_PLAY_PAUSE:   "KEYCODE_MEDIA_PLAY_PAUSE",
	KEYCODE_MEDIA_STOP:         "KEYCODE_MEDIA_STOP",
	KEYCODE_MEDIA_NEXT:         "KEYCODE_MEDIA_NEXT",
	KEYCODE_MEDIA_PREVIOUS:     "KEYCODE_MEDIA_PREVIOUS",
	KEYCODE_MEDIA_REWIND:       "KEYCODE_MEDIA_REWIND",
	KEYCODE_MEDIA_FAST_FORWARD: "KEYCODE_MEDIA_FAST_FORWARD",
	KEYCODE_MUTE:               "KEYCODE_MUTE",
}
